name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python deps
        run: |
          pip install flask requests pytest
          pip list

      - name: Run pytest
        run: pytest -v

      - name: Install OPA
        run: |
          curl -sL https://openpolicyagent.org/downloads/v1.1.0/opa_linux_amd64_static -o /usr/local/bin/opa
          chmod +x /usr/local/bin/opa
          opa version

      - name: Run OPA tests
        run: opa test gateway/opa/ -v
